# ┌────────────────────────────┐
# │     Oh My Zsh Settings     │
# └────────────────────────────┘

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="wezm+"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(brew git)

source "$ZSH/oh-my-zsh.sh"

# ┌────────────────────────────┐
# │       General Config       │
# └────────────────────────────┘

alias lsl="ls -l"
alias mount_venus="/usr/bin/osascript -e 'try' -e 'mount volume \"smb://jungaretti@helium.local/Venus\"' -e 'end try'"
alias backup_honeycrisp="crestic honeycrisp@b2 backup && mount_venus && crestic honeycrisp@nas backup"

export EDITOR=vim

# Fix git commit signing
export GPG_TTY="$(tty)"

# Add npm to PATH via fnm
if [ -n "$(command -v fnm)" ]; then
  eval "$(fnm env)"
fi

# ┌────────────────────────────┐
# │     Codespaces Config      │
# └────────────────────────────┘

ms_alias="jpungaretti"
cs_settings_file="$HOME/codespaces-settings.json"

cs_export() {
  export VSCS_TARGET="$(jq -r '.vscsTarget // ""' $cs_settings_file)"
  export VSCS_LOCATION="$(jq -r '.vscsRegion // ""' $cs_settings_file)"

  # VSCS_TARGET_URL must be empty unless VSCS_TARGET is 'local'
  export VSCS_TARGET_URL=""
  if [ "$VSCS_TARGET" = 'local' ]; then
    VSCS_TARGET_URL="$(jq -r '.vscsTargetUrl // ""' $cs_settings_file)"
  fi
}

cs_print() {
  local target="prod"
  local location="default"

  # VSCS_TARGET and VSCS_LOCATION are empty when using default settings
  if [ -n "$VSCS_TARGET" ]; then
    target="$VSCS_TARGET"
  fi
  if [ -n "$VSCS_LOCATION" ]; then
    location="$VSCS_LOCATION"
  fi

  echo "Codespaces target: $target ($location)"
}

cs_update() {
  local target="${1:-prod}"

  if [ -z "$ms_alias" ]; then
    echo "You must set your Microsoft alias before updating Codespaces settings"
    return 1
  fi

  if [ ! -e "$cs_settings_file" ]; then
    jq -n '{isInternal: true, logTelemetry: true}' >"$cs_settings_file"
    echo "Created new settings file: $cs_settings_file"
  fi

  local vscs_target=""
  local vscs_target_url=""
  local vscs_region=""
  case $target in
  "local")
    vscs_target="local"
    vscs_target_url="https://codespaces.servicebus.windows.net/$ms_alias"
    vscs_region="WestUs2"
    ;;
  "dev")
    vscs_target="development"
    vscs_target_url="https://online.dev.core.vsengsaas.visualstudio.com"
    vscs_region="WestUs2"
    ;;
  "ppe")
    vscs_target="ppe"
    vscs_target_url="https://online-ppe.core.vsengsaas.visualstudio.com"
    vscs_region="WestUs2"
    ;;
  "prod")
    # Use empty strings for default settings
    ;;
  *)
    echo "Unknown target: $target"
    return 1
    ;;
  esac

  # Update Codespaces config file
  local temp="$(mktemp)"
  jq --arg target "$vscs_target" --arg targetUrl "$vscs_target_url" --arg region "$vscs_region" '. += {vscsTarget: $target, vscsTargetUrl: $targetUrl, vscsRegion: $region}' "$cs_settings_file" >"$temp"
  mv "$temp" "$cs_settings_file"

  # Update VSCS environment variables
  cs_export

  cat "$cs_settings_file"
}
export cs_update

if command -v complete &>/dev/null; then
  complete -W "local dev ppe prod" cs_update
fi

alias config_cs="cs_update"

# Read existing Codespaces settings
if [ -e "$cs_settings_file" ]; then
  cs_export && cs_print
fi
